### PR TITLE
Make all PR data available to templates

### PR DESCRIPTION
**Pull request by nedbat**
This way I can add info like `{{ pr.title }}`.

This also adjusts "action" so that it reports "merged" instead of "closed" for merged pull requests.

### CODE REVIEW

**Comment by nedbat** [comment]
BTW, this is already running on Heroku :)

**Comment by nedbat** [comment]
@lgp171188 ?

**Comment by lgp171188** [comment]
@nedbat, I didn't get notified about the PR before you pinged me. Sorry! The changes look good to me. I will do a quick test today and merge this. Thanks!

**Review by lgp171188 — APPROVED** [review]
:+1: 
- [x] I tested this and verified that this works as expected.
- [x] I read through the code

**Pull request merged**
